### PR TITLE
Fix 0.4 deprecation warnings

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by andrewcooke** [comment]
ha!  i'm afraid we were both working on this at exactly the same time.  i am trying to commit my changes right now, but having to do the github delete token dance.  sorry / thanks!

**Comment by andrewcooke** [comment]
oh, but you have the syntax for ==, which i couldn't work out.  is it ok if i copy that?

**Comment by yuyichao** [comment]
Sure. Please feel free to copy what you need from this and close the PR.

**Comment by andrewcooke** [comment]
thanks; credited you in the readme for release 0.0.7

**Pull request closed without merging**
